// <auto-generated />
using System;
using Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tasApi.Migrations
{
    [DbContext(typeof(TasDB))]
    partial class TasDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Choice", b =>
                {
                    b.Property<int>("_Id")
                        .HasColumnType("int");

                    b.Property<int?>("NextSceneId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnSceneId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_Id");

                    b.HasIndex("NextSceneId");

                    b.HasIndex("OwnSceneId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("Entities.Models.Scene", b =>
                {
                    b.Property<int>("_Id")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("storyId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("Entities.Models.SceneEffect", b =>
                {
                    b.Property<int>("_Id")
                        .HasColumnType("int");

                    b.Property<int?>("goldChange")
                        .HasColumnType("int");

                    b.Property<int?>("hpChange")
                        .HasColumnType("int");

                    b.Property<int>("sceneId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("sceneId")
                        .IsUnique();

                    b.ToTable("SceneEffects");
                });

            modelBuilder.Entity("Entities.Models.Choice", b =>
                {
                    b.HasOne("Entities.Models.Scene", "NextScene")
                        .WithMany("PrecidingChoices")
                        .HasForeignKey("NextSceneId");

                    b.HasOne("Entities.Models.Scene", "OwnScene")
                        .WithMany("OwnChoices")
                        .HasForeignKey("OwnSceneId");

                    b.Navigation("NextScene");

                    b.Navigation("OwnScene");
                });

            modelBuilder.Entity("Entities.Models.SceneEffect", b =>
                {
                    b.HasOne("Entities.Models.Scene", "Scene")
                        .WithOne("SceneEffect")
                        .HasForeignKey("Entities.Models.SceneEffect", "sceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Entities.Models.Scene", b =>
                {
                    b.Navigation("OwnChoices");

                    b.Navigation("PrecidingChoices");

                    b.Navigation("SceneEffect");
                });
#pragma warning restore 612, 618
        }
    }
}
